Branch charles 155
marcosdosea/MaisMarinha pull request #156
Opened 2022-10-01 00:01 UTC by charlescosta1

2022-10-02 18:33 UTC, carloshldj reviewed
Revisando

2022-10-02 18:39 UTC, carloshldj requested changes
Você criou a classe CapitaniaService, e implementou a Classe AtendimentoService, que é de outra issue, verifique por favor, a implementação da outra issue está certa, associe ela a mesma branch

2022-10-02 18:41 UTC, charlescosta1 commented
Entendido, Carlos. Vou fazer isso.

2022-10-03 01:31 UTC, carloshldj approved these changes
Certo

2022-10-03 01:31 UTC, merged